Fix compilation in Python 3.x environments Commit 86111d97badaf1c4f9e73583bd637b4977372fd6 seems to break Python 3 compatibility
$ make
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security -D_FORTIFY_SOURCE=2 -fPIC -I/usr/local/include -I/usr/include/python3.5m -I/srv/ven35/include/python3.5m -c getdns.c -o build/temp.linux-x86_64-3.5/getdns.o -g
getdns.c: In function ‘wire_to_dict’:
getdns.c:336:5: warning: implicit declaration of function ‘PyBuffer_Check’ [-Wimplicit-function-declaration]
     if (!PyBuffer_Check(py_wirebuf))  {